"""Classroom Quiz · Node 10 — generate_variants.

For each BASE question (one per LO), produce 4–10 objective-bound variants along two axes:
  • THEORY axis (backbone): same format-family, different cognitive ANGLE on the same
    assertion — gated by the concept's Bloom tier so we never over-reach taught depth.
  • FORMAT axis (opportunistic): recast the assertion into a different question TYPE
    (MCQ ↔ T/F ↔ FIB ↔ code-analysis), code types only when the session shows code.

A deterministic, diversity-first planner enumerates (angle × type) specs; each variant is
GENERATED BY THE EXISTING m08 type-agents (reusing every grounding/option/code guard) by
steering the LO with a variant directive. Two gates then run per candidate: a deterministic
DEDUP (vs the base + accepted variants) and an LLM OBJECTIVE-FIDELITY judge (drop drift).
Clamp [4,10]; if fewer than 4 distinct, defensible variants survive, emit what we have and
report the shortfall (never pad with near-duplicates).

Runs at the RUNNER level, after the graph (see cq_runner), sharing the run's adapter.
"""
from __future__ import annotations

from pydantic import BaseModel, Field

from app.core.config import settings
from app.mcq_pipeline.config import EXCLUDED_QUESTION_TYPES
from app.mcq_pipeline.prompts.store import get_prompt
from app.mcq_pipeline.utils import scope
from app.mcq_pipeline.utils.concurrency import pmap
from app.mcq_pipeline.nodes.m08_generate_questions.node import generate_lean
from app.mcq_pipeline.nodes.m10_generate_variants.prompts import (
    _DIRECTIVE, _FIDELITY_SYS, _OBJECTIVE_SYS,
)

CQ_VARIANT_MIN = 4
CQ_VARIANT_MAX = 10
# Bases are expanded concurrently. Kept below the m08 default (8) because each base fires
# several LLM calls (generate_lean + fidelity judge per spec), so this bounds provider load.
CQ_VARIANT_WORKERS = 4

# Theory angles per Bloom tier (cumulative: a tier includes all lower tiers' angles). Each angle
# is (key, default_type, instruction). Gating by the LO's clamped tier keeps us within taught depth.
_THEORY_ANGLES = {
    "remember": [
        ("definition", "MULTIPLE_CHOICE", "ask which option best DEFINES the concept"),
        ("property", "MULTIPLE_CHOICE", "ask which option states a correct PROPERTY/characteristic of it"),
        ("example", "MULTIPLE_CHOICE", "ask which option is a correct EXAMPLE/instance of it"),
        ("non_example", "MULTIPLE_CHOICE", "ask which option is NOT an example of it (odd-one-out)"),
        ("true_false_claim", "TRUE_OR_FALSE", "state the assertion as one claim to judge true/false"),
    ],
    "understand": [
        ("compare", "MULTIPLE_CHOICE", "ask how it DIFFERS from a closely related concept"),
        ("purpose", "MULTIPLE_CHOICE", "ask WHY it is used / what problem it solves"),
        ("misconception", "TRUE_OR_FALSE", "state a common MISCONCEPTION about it as a claim to judge"),
        ("classify", "MULTIPLE_CHOICE", "ask the learner to CLASSIFY which case it applies to"),
    ],
    "apply": [
        ("best_fit", "MULTIPLE_CHOICE", "give a short SCENARIO and ask which option correctly applies it"),
        ("predict", "MULTIPLE_CHOICE", "ask the learner to PREDICT the result of applying it"),
        ("choose_approach", "MULTIPLE_CHOICE", "ask which APPROACH correctly uses it for a stated goal"),
    ],
    "scenario": [
        ("diagnose", "MULTIPLE_CHOICE", "give a situation and ask the learner to DIAGNOSE using it"),
        ("recommend", "MULTIPLE_CHOICE", "ask which RECOMMENDATION correctly applies it in a novel situation"),
    ],
}
_TIER_ORDER = ("remember", "understand", "apply", "scenario")

# Format-axis catalog (TEXTUAL / CODE_ANALYSIS_TEXTUAL already excluded — exact-string-match types).
_FORMAT_CATALOG = [
    "MULTIPLE_CHOICE", "TRUE_OR_FALSE", "MORE_THAN_ONE_MULTIPLE_CHOICE",
    "CODE_ANALYSIS_MULTIPLE_CHOICE", "CODE_ANALYSIS_MORE_THAN_ONE_MULTIPLE_CHOICE", "FIB_CODING",
]
_CODE_TYPES = {"CODE_ANALYSIS_MULTIPLE_CHOICE", "CODE_ANALYSIS_MORE_THAN_ONE_MULTIPLE_CHOICE", "FIB_CODING"}


# --- small structured schemas for the two judgment calls -------------------- #
class _Objective(BaseModel):
    assertion: str = Field(description="the single proposition/skill the correct answer proves")
    bloom_tier: str = Field(description="remember | understand | apply | scenario")


class _Fidelity(BaseModel):
    same_objective: bool = Field(description="true only if the variant proves the SAME assertion")
    reason: str = Field(default="", description="one short sentence")


def _judge_model():
    from app.mcq_pipeline.utils.llm import make_chat_model
    return make_chat_model(temperature=0, model=settings.mcq_review_model or None)


def _norm_tier(value: str) -> str:
    v = (value or "").strip().lower()
    if v in _TIER_ORDER:
        return v
    return {"remembering": "remember", "understanding": "understand", "applying": "apply",
            "analyzing": "understand", "evaluating": "scenario", "creating": "scenario"}.get(v, "understand")


def _angles_up_to(tier: str) -> list[tuple[str, str, str]]:
    out: list[tuple[str, str, str]] = []
    for t in _TIER_ORDER:
        out.extend(_THEORY_ANGLES.get(t, []))
        if t == tier:
            break
    return out


def _eligible_format_types(base_type: str, *, has_code: bool, is_sql: bool) -> list[str]:
    out = []
    for t in _FORMAT_CATALOG:
        if t in EXCLUDED_QUESTION_TYPES or t == base_type:
            continue
        if t in _CODE_TYPES and not has_code:
            continue
        if t == "FIB_CODING" and is_sql:           # SQL apply uses code-analysis, not FIB_CODING
            continue
        out.append(t)
    return out


def _plan_specs(base_type: str, tier: str, *, has_code: bool, is_sql: bool,
                max_n: int) -> list[dict]:
    """Diversity-first variant specs: interleave distinct theory angles and distinct format
    recasts so each cell is a different (angle × type) before any repeats. Capped with a small
    buffer over max_n to absorb dedup/fidelity drops."""
    theory = []
    for key, qtype, instr in _angles_up_to(tier):
        # A 'predict the result' angle becomes a code-analysis question when the session has code.
        if key == "predict" and has_code:
            qtype = "CODE_ANALYSIS_MULTIPLE_CHOICE"
        if qtype in EXCLUDED_QUESTION_TYPES:
            continue
        theory.append({"axis": "theory", "type": qtype, "angle": key, "instruction": instr})

    fmt = [{"axis": "format", "type": t, "angle": f"recast_as_{t.lower()}",
            "instruction": f"recast the SAME assertion as a {t} question"}
           for t in _eligible_format_types(base_type, has_code=has_code, is_sql=is_sql)]

    specs, i, j = [], 0, 0
    while (i < len(theory) or j < len(fmt)) and len(specs) < max_n + 3:
        if i < len(theory):
            specs.append(theory[i]); i += 1
        if j < len(fmt) and len(specs) < max_n + 3:
            specs.append(fmt[j]); j += 1
    return specs


def _stem_of(q: dict) -> str:
    lean = q.get("lean") or {}
    return (lean.get("question") or lean.get("statement") or "").strip()


def _correct_of(lean: dict, qtype: str) -> str:
    if qtype in ("MULTIPLE_CHOICE", "MORE_THAN_ONE_MULTIPLE_CHOICE"):
        return " | ".join(o.get("content", "") for o in (lean.get("options") or []) if o.get("is_correct"))
    if qtype == "TRUE_OR_FALSE":
        return f"{'True' if lean.get('is_true') else 'False'}: {lean.get('statement', '')}"
    if qtype == "CODE_ANALYSIS_MULTIPLE_CHOICE":
        return lean.get("correct_output", "")
    if qtype == "CODE_ANALYSIS_MORE_THAN_ONE_MULTIPLE_CHOICE":
        return " | ".join(lean.get("correct_outputs") or [])
    if qtype == "FIB_CODING":
        return f"{lean.get('blank_answer', '')} -> {lean.get('test_output', '')}"
    if qtype == "TEXTUAL":
        return lean.get("answer", "")
    if qtype == "REARRANGE":
        return " ; ".join(lean.get("ordered_items") or [])
    return ""


def _tokens(text: str) -> set[str]:
    import re
    return {t for t in re.findall(r"\w+", (text or "").lower()) if len(t) > 2}


def _too_similar(stem: str, seen: list[str], threshold: float = 0.82) -> bool:
    a = _tokens(stem)
    if not a:
        return True            # an empty stem is useless — treat as duplicate
    for s in seen:
        b = _tokens(s)
        if not b:
            continue
        jac = len(a & b) / max(1, len(a | b))
        if jac >= threshold:
            return True
    return False


def derive_objective(base: dict) -> dict:
    """Extract the invariant a base question assesses (the assertion + Bloom tier). Falls back
    to the stem when the judge call fails (degrade, never crash the run)."""
    lean = base.get("lean") or {}
    qtype = base.get("question_type", "")
    payload = (f"TYPE: {qtype}\nSTEM: {_stem_of(base)}\n"
               f"CORRECT ANSWER: {_correct_of(lean, qtype)}\n"
               f"EXPLANATION: {lean.get('explanation', '')}")
    try:
        obj: _Objective = _judge_model().with_structured_output(_Objective).invoke([
            {"role": "system", "content": get_prompt("cq.variants.objective", _OBJECTIVE_SYS)},
            {"role": "user", "content": payload},
        ])
        assertion = (obj.assertion or "").strip()
        if assertion:
            return {"assertion": assertion, "bloom_tier": _norm_tier(obj.bloom_tier)}
    except Exception:  # noqa: BLE001 — degrade to the stem rather than break variant generation
        pass
    return {"assertion": _stem_of(base) or base.get("outcome", ""), "bloom_tier": "understand"}


def _fidelity_ok(objective: dict, variant: dict) -> bool:
    lean = variant.get("lean") or {}
    qtype = variant.get("question_type", "")
    payload = (f"ASSERTION (the invariant): {objective.get('assertion', '')}\n\n"
               f"VARIANT TYPE: {qtype}\nVARIANT STEM: {_stem_of(variant)}\n"
               f"VARIANT CORRECT ANSWER: {_correct_of(lean, qtype)}\n"
               f"VARIANT EXPLANATION: {lean.get('explanation', '')}")
    try:
        verdict: _Fidelity = _judge_model().with_structured_output(_Fidelity).invoke([
            {"role": "system", "content": get_prompt("cq.variants.fidelity", _FIDELITY_SYS)},
            {"role": "user", "content": payload},
        ])
        return bool(verdict.same_objective)
    except Exception:  # noqa: BLE001 — an infra failure shouldn't silently discard a good variant
        return True


def _make_variant(spec: dict, lo: dict, objective: dict, base_key: str, idx: int) -> dict | None:
    directive = get_prompt("cq.variants.directive", _DIRECTIVE).format(
        assertion=objective.get("assertion", ""), bloom=objective.get("bloom_tier", ""),
        axis=spec["axis"], angle_instruction=spec["instruction"])
    lo_v = {**lo, "question_type": spec["type"],
            "description": (lo.get("description") or "") + directive}
    try:
        res = generate_lean(lo_v, fallback_uncovered=True)   # reuse all m08 creation-time guards
    except Exception:  # noqa: BLE001 — a single variant must never abort the batch
        return None
    if res.get("status") != "generated" or not res.get("lean"):
        return None
    res["outcome"] = lo.get("outcome")
    res["is_variant"] = True
    res["base_question_key"] = base_key
    res["question_key"] = f"{base_key}::v{idx}"
    res["variant_axis"] = spec["axis"]
    res["variant_angle"] = spec["angle"]
    res["objective"] = objective
    return res


def generate_variants_for_questions(
    los: list[dict], questions: list[dict], *, adapter,
    min_n: int = CQ_VARIANT_MIN, max_n: int = CQ_VARIANT_MAX, on_progress=None,
    workers: int = CQ_VARIANT_WORKERS,
) -> tuple[list[dict], list[dict]]:
    """Expand every generated base question into objective-bound variants.

    Bases are independent, so they run CONCURRENTLY (pmap rebinds the bound adapter into each
    worker thread). Within a base, specs stay sequential — the dedup gate (`seen`) and the
    `max_n` early-stop depend on which variants were already accepted. Returns (variants,
    shortfalls) where shortfalls = [{base_question_key, outcome, produced, target_min}] for any
    base that couldn't reach `min_n` distinct defensible variants."""
    scope.set_adapter(adapter)                     # generate_lean grounds via the bound adapter
    has_code = bool(getattr(adapter, "has_code", False))
    is_sql = (getattr(adapter, "domain", "") or "").upper() == "SQL"
    lo_by_outcome = {lo.get("outcome"): lo for lo in los}
    bases = [q for q in questions if q.get("status") == "generated"]

    def _variants_for_base(base: dict) -> tuple[list[dict], dict | None]:
        """All accepted variants for ONE base + an optional shortfall record. Mutates only this
        base's own dict, so it's safe to run concurrently across bases."""
        lo = lo_by_outcome.get(base.get("outcome"))
        base_key = base.get("question_key") or base.get("outcome") or ""
        base["question_key"] = base_key
        base["is_variant"] = False
        if lo is None:
            if on_progress:
                on_progress()
            return [], None
        objective = derive_objective(base)
        base["objective"] = objective
        tier = _norm_tier(objective.get("bloom_tier") or lo.get("bloom_category"))
        specs = _plan_specs(base.get("question_type", ""), tier,
                            has_code=has_code, is_sql=is_sql, max_n=max_n)
        accepted: list[dict] = []
        seen = [_stem_of(base)]
        for spec in specs:
            if len(accepted) >= max_n:
                break
            v = _make_variant(spec, lo, objective, base_key, len(accepted) + 1)
            if v is None:
                continue
            vstem = _stem_of(v)
            if _too_similar(vstem, seen):
                continue
            if not _fidelity_ok(objective, v):
                continue
            seen.append(vstem)
            accepted.append(v)
        base["variant_count"] = len(accepted)
        shortfall = None
        if len(accepted) < min_n:
            shortfall = {"base_question_key": base_key, "outcome": base.get("outcome"),
                         "produced": len(accepted), "target_min": min_n}
        if on_progress:
            on_progress()
        return accepted, shortfall

    results = pmap(_variants_for_base, bases, workers=workers)
    variants = [v for accepted, _ in results for v in accepted]
    shortfalls = [s for _, s in results if s is not None]
    return variants, shortfalls
