"""Classroom Quiz · Node 10 — generate_variants · prompts.

Three DB-overridable prompts:
  - cq.variants.objective  — derive the invariant a base question assesses (the "assertion").
  - cq.variants.directive   — the steering block injected into a variant's LO so the reused
                              m08 generator produces the SAME assertion via a new angle/format.
  - cq.variants.fidelity    — the objective-fidelity judge (drop variants that drift off-objective).

The variant questions themselves are generated by the EXISTING m08 type-agents (reusing every
grounding/option/code guard); these prompts only derive the objective, steer, and gate.
"""
from __future__ import annotations

from app.mcq_pipeline.prompts.store import register

_OBJECTIVE_SYS = register("cq.variants.objective", """You analyze a single assessment question and extract the ONE thing its correct answer proves — its assessment objective.

Return:
- assertion: a single precise sentence stating exactly what a learner demonstrates by answering correctly (the proposition or skill under test). NOT the topic — the specific claim/decision. E.g. "a Python list is mutable while a tuple is not", not "Python data types".
- bloom_tier: one of remember | understand | apply | scenario — the cognitive level the question operates at.

The assertion is the INVARIANT every variant must preserve. Be specific and self-contained (no "this code", "the above") so it can stand alone.""")

# Injected into a variant's LO `description` so the reused m08 agent stays on-objective.
# Formatted with: assertion, bloom, axis, angle_instruction.
_DIRECTIVE = register("cq.variants.directive", """

=== VARIANT DIRECTIVE (CLASSROOM QUIZ — read carefully) ===
You are writing a VARIANT of an existing base question. It MUST assess the SAME objective:
  ASSERTION (what the correct answer must prove): {assertion}
Rules:
- Keep the Bloom level identical ({bloom}). Do NOT drift to a different fact, sub-concept, or skill.
- The correct answer must hinge on EXACTLY the assertion above — not a tangential or adjacent fact.
- Change ONLY the {axis}: {angle_instruction}
- Stay grounded strictly in the course material provided; invent nothing the session did not teach.
- Make it genuinely different in surface form from a plain restatement — a learner who has the base question memorised must still have to reason about the assertion.""")

_FIDELITY_SYS = register("cq.variants.fidelity", """You are an objective-fidelity judge for classroom-quiz question variants.

You are given a base question's ASSERTION (the proposition its correct answer proves) and a candidate VARIANT question (stem, correct answer, explanation). Decide whether answering the variant correctly proves the SAME assertion at the SAME cognitive level.

Return:
- same_objective: true ONLY if the variant's correct answer turns on the SAME assertion (same proposition/skill), not a different fact, a tangential detail, or a different Bloom intent.
- reason: one short sentence.

Be strict: a well-formed question about a DIFFERENT (even adjacent) point is NOT a faithful variant — return false. When unsure, return false.""")
