# Generated by Django 6.0.6 on 2026-06-08 14:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('course_name', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('duration', models.CharField(blank=True, max_length=64)),
                ('multimedia_url', models.URLField(blank=True, max_length=1000)),
                ('course_category', models.CharField(blank=True, max_length=255)),
                ('course_link', models.URLField(blank=True, max_length=1000)),
                ('selected_courseversion_id', models.CharField(blank=True, max_length=64)),
                ('selected_version_id', models.CharField(blank=True, max_length=64)),
                ('is_latest_version', models.BooleanField(default=False)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SyncJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_id', models.CharField(max_length=64)),
                ('courseversion_id', models.CharField(blank=True, max_length=64)),
                ('version_id', models.CharField(blank=True, max_length=64)),
                ('is_latest_version', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure')], default='PENDING', max_length=16)),
                ('message', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_id', models.CharField(max_length=64)),
                ('topic_name', models.CharField(blank=True, max_length=500)),
                ('topic_link', models.URLField(blank=True, max_length=1000)),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='courses.course')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.CharField(max_length=64)),
                ('unit_name', models.CharField(blank=True, max_length=500)),
                ('unit_type', models.CharField(blank=True, max_length=64)),
                ('unit_link', models.URLField(blank=True, max_length=1000)),
                ('error', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='courses.topic')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
