# Generated by Django 6.0.6 on 2026-06-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='environment',
            field=models.CharField(default='PROD', max_length=16),
        ),
        migrations.AddField(
            model_name='syncjob',
            name='environment',
            field=models.CharField(default='PROD', max_length=16),
        ),
    ]
