# Generated by Django 6.0.6 on 2026-06-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_environment_syncjob_environment'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='has_reading_material',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='reading_material_link',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='unit',
            name='reading_material_name',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='unit',
            name='reading_material_unit_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
