# Generated by Django 6.0.6 on 2026-06-08 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_unit_has_reading_material_unit_reading_material_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='error',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='has_reading_material',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='reading_material_link',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='reading_material_name',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='reading_material_unit_id',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='unit_id',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='unit_link',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='unit_name',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='unit_type',
        ),
        migrations.AddField(
            model_name='unit',
            name='kind',
            field=models.CharField(choices=[('SESSION', 'Session'), ('QUIZ', 'Quiz'), ('PRACTICE', 'Practice'), ('SINGLE', 'Single')], default='SINGLE', max_length=16),
        ),
        migrations.AddField(
            model_name='unit',
            name='label',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='UnitPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=64)),
                ('unit_id', models.CharField(max_length=64)),
                ('unit_type', models.CharField(blank=True, max_length=64)),
                ('name', models.CharField(blank=True, max_length=500)),
                ('link', models.URLField(blank=True, max_length=1000)),
                ('error', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='courses.unit')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
