# Generated by Django 6.0.6 on 2026-06-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_unit_error_remove_unit_has_reading_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='required_by', to='courses.course'),
        ),
        migrations.AddField(
            model_name='syncjob',
            name='prerequisite_for',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='unit',
            name='kind',
            field=models.CharField(choices=[('SESSION', 'Session'), ('PRACTICE', 'Practice'), ('SINGLE', 'Single')], default='SINGLE', max_length=16),
        ),
    ]
