# Generated by Django 6.0.6 on 2026-06-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_prerequisites_syncjob_prerequisite_for_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='content_extracted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syncjob',
            name='job_type',
            field=models.CharField(choices=[('SYNC', 'Sync'), ('EXTRACT', 'Extract')], default='SYNC', max_length=16),
        ),
        migrations.AddField(
            model_name='unitpart',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='unitpart',
            name='content_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='unitpart',
            name='content_extracted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unitpart',
            name='content_status',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
